import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
const state=vi.hoisted(()=>({auth:{tenantId:'t',userId:'owner',role:'owner'} as any}));
vi.mock('../src/utils/auth',()=>({requireDashboard:async(c:any)=>{c.set('auth',state.auth);return state.auth;}}));
import { formRoutes,expireFormAnswers } from '../src/routes/forms';
import { formSchema,validateAnswers } from '../src/services/forms';
import { encryptText } from '../src/utils/crypto';
class Statement{values:any[]=[];constructor(readonly db:DatabaseSync,readonly sql:string){}bind(...v:any[]){this.values=v;return this;}async first(){return this.db.prepare(this.sql).get(...this.values)||null;}async all(){return {results:this.db.prepare(this.sql).all(...this.values)};}execute(){return {meta:{changes:Number(this.db.prepare(this.sql).run(...this.values).changes)}};}async run(){return this.execute();}}
class Db{raw=new DatabaseSync(':memory:');prepare(sql:string){return new Statement(this.raw,sql);}async batch(statements:Statement[]){this.raw.exec('BEGIN');try{const rows=statements.map(s=>s.execute());this.raw.exec('COMMIT');return rows;}catch(e){this.raw.exec('ROLLBACK');throw e;}}}
let db:Db,env:any;const base='/v1/projects/p/chat-services/s/forms';
const request=(path:string,body?:unknown,token?:string,method?:string)=>formRoutes.request('https://app.test'+path,{method:method||(body===undefined?'GET':'POST'),headers:{Origin:'https://app.test','Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})},env);
const definition=()=>({title:'Support request',description:'Tell us what happened.',retention_days:2,fields:[{key:'email',label:'Email',type:'email',required:true},{key:'category',label:'Category',type:'select',options:['Product','Other'],required:true},{key:'details',label:'Details',type:'textarea',required:true,show_if:{field:'category',equals:'Other'}}]});
async function enabled(){db.raw.exec(`UPDATE platform_settings SET value_json='{"enabled":true,"stop":"immediate","reason":""}' WHERE key='feature.forms'`);}
async function create(def:any=definition()){const response=await request(base,def);expect(response.status).toBe(201);return (await response.json() as any).id;}
async function activate(id:string){expect((await request(base+'/'+id+'/publish',{revision:1})).status).toBe(200);expect((await request(base+'/'+id+'/status',{active:true})).status).toBe(200);}
async function start(id:string){const r=await request('/v1/public-forms/'+id+'/start',{});expect(r.status).toBe(201);return r.json() as Promise<any>;}
async function submit(token:string,answers:any){const r=await request('/v1/form-session/review',{revision:0,answers},token);expect(r.status).toBe(200);const review=await r.json() as any;const receipt=await request('/v1/form-session/submit',{revision:review.revision,confirm:true},token);expect(receipt.status).toBe(200);return receipt.json() as Promise<any>;}
beforeEach(async()=>{db=new Db();state.auth={tenantId:'t',userId:'owner',role:'owner'};for(const file of ['0001_initial.sql','0002_usage_ledger.sql','002_billing_and_ai_credits.sql','002_configurable_billing.sql','0006_chat_services.sql','027_webchat_telegram_onboarding.sql','032_staff_portals.sql','033_business_connectors.sql','034_interactive_forms.sql'])db.raw.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8'));db.raw.exec(`INSERT INTO tenants(id,name,slug,created_at,updated_at) VALUES('t','Tenant','tenant',0,0),('other','Other','other',0,0);INSERT INTO projects(id,tenant_id,name,created_at,updated_at) VALUES('p','t','Project',0,0);INSERT INTO chat_services(id,tenant_id,project_id,name,created_at,updated_at) VALUES('s','t','p','Support',0,0);`);env={DB:db,MASTER_KEY:'01'.repeat(32),CORS_ORIGINS:'https://app.test'};});
afterEach(()=>{db.raw.close();vi.restoreAllMocks();});
describe('interactive forms journey',()=>{
 it('keeps new forms disabled until platform activation and restricts management',async()=>{
  expect((await request(base,definition())).status).toBe(403);await enabled();const id=await create();state.auth.role='developer';expect((await request(base)).status).toBe(403);state.auth={tenantId:'other',userId:'foreign',role:'owner'};expect((await request(base+'/'+id+'/submissions')).status).toBe(403);
 });
 it('validates condition order, duplicate keys and typed visible answers',()=>{
  expect(formSchema.safeParse({...definition(),fields:[{key:'x',label:'X',type:'text',show_if:{field:'later',equals:'yes'}}]}).success).toBe(false);
  expect(formSchema.safeParse({...definition(),fields:[definition().fields[0],definition().fields[0]]}).success).toBe(false);
  const schema=formSchema.parse(definition());expect(validateAnswers(schema,{email:'wrong',category:'Other'}).errors).toHaveProperty('email');expect(validateAnswers(schema,{email:'a@example.test',category:'Other'}).errors).toHaveProperty('details');expect(validateAnswers(schema,{email:'a@example.test',category:'Product',details:'private hidden answer',unknown:'discard'}).answers).toEqual({email:'a@example.test',category:'Product'});
  const typed=formSchema.parse({title:'Typed',fields:[{key:'quantity',label:'Quantity',type:'number',min:1,max:10,required:true},{key:'date',label:'Date',type:'date',required:true},{key:'consent',label:'Confirm',type:'checkbox',required:true}]});
  expect(Object.keys(validateAnswers(typed,{quantity:11,date:'2026-02-31',consent:false}).errors)).toHaveLength(3);
  expect(validateAnswers(typed,{quantity:2,date:'2026-09-11',consent:true}).errors).toEqual({});
 });
 it('requires publication and activation and pins customer sessions to immutable versions',async()=>{
  await enabled();const id=await create();expect((await request(base+'/'+id+'/status',{active:true})).status).toBe(409);expect((await request('/v1/public-forms/'+id+'/start',{})).status).toBe(404);await activate(id);const first=await start(id);
  const changed={...definition(),title:'Updated form'};expect((await request(base+'/'+id,{revision:1,definition:changed},undefined,'PUT')).status).toBe(200);expect((await request(base+'/'+id,{revision:1,definition:changed},undefined,'PUT')).status).toBe(409);expect((await request(base+'/'+id+'/status',{active:true})).status).toBe(409);await request(base+'/'+id+'/publish',{revision:2});expect((await start(id)).definition.title).toBe('Updated form');expect((await (await request('/v1/form-session',undefined,first.token)).json() as any).definition.title).toBe('Support request');
 });
 it('collects, validates, reviews and submits once with an encrypted receipt',async()=>{
  await enabled();const id=await create();await activate(id);const s=await start(id);expect((await request('/v1/form-session/submit',{revision:1,confirm:true},s.token)).status).toBe(409);const invalid=await request('/v1/form-session/review',{revision:0,answers:{email:'bad',category:'Other'}},s.token);expect(invalid.status).toBe(422);
  const result=await submit(s.token,{email:'customer@example.test',category:'Other',details:'Private issue'});expect((await (await request('/v1/form-session/submit',{revision:1,confirm:true},s.token)).json() as any).reference).toBe(result.reference);expect((await request('/v1/form-session/review',{revision:1,answers:{}},s.token)).status).toBe(422);const row=db.raw.prepare('SELECT * FROM form_sessions').get() as any;expect(row.encrypted_answers).not.toContain('Private issue');expect(row.token_hash).not.toContain(s.token);expect(db.raw.prepare('SELECT * FROM usage_events').all()).toHaveLength(0);
  const detail=await (await request(base+'/'+id+'/submissions/'+result.reference)).json() as any;expect(detail.answers.details).toBe('Private issue');expect(db.raw.prepare("SELECT * FROM audit_logs WHERE action='form.answers_viewed'").all()).toHaveLength(1);
 });
 it('enforces deactivation, retirement cutoff and tenant denial on existing sessions',async()=>{
  await enabled();const id=await create();await activate(id);const s=await start(id);db.raw.prepare('UPDATE platform_settings SET value_json=? WHERE key=?').run(JSON.stringify({enabled:false,stop:'finish_existing',reason:'Retire',disabled_at:Date.now()+1000}),'feature.forms');expect((await request('/v1/public-forms/'+id+'/start',{})).status).toBe(403);expect((await request('/v1/form-session',undefined,s.token)).status).toBe(200);db.raw.exec(`INSERT INTO platform_settings VALUES('feature-tenant.t.forms','{"enabled":false}',1,'admin',0)`);expect((await request('/v1/form-session',undefined,s.token)).status).toBe(403);db.raw.exec("DELETE FROM platform_settings WHERE key='feature-tenant.t.forms'");await request(base+'/'+id+'/status',{active:false});expect((await request('/v1/form-session',undefined,s.token)).status).toBe(403);
 });
 it('keeps reviewed drafts private until explicit submission',async()=>{
  await enabled();const id=await create();await activate(id);const s=await start(id);
  expect((await request('/v1/form-session/review',{revision:0,answers:{email:'private@example.test',category:'Product'}},s.token)).status).toBe(200);
  expect((await (await request(base+'/'+id+'/submissions/'+s.id)).json() as any).answers).toBeNull();
  await request('/v1/form-session/submit',{revision:1,confirm:true},s.token);
  expect((await (await request(base+'/'+id+'/submissions/'+s.id)).json() as any).answers.email).toBe('private@example.test');
 });
 it('expires retained answers and never exposes them to another session',async()=>{
  await enabled();const id=await create();await activate(id);const a=await start(id),b=await start(id);await submit(a.token,{email:'a@example.test',category:'Product'});expect((await (await request('/v1/form-session',undefined,b.token)).json() as any).answers).toEqual({});expect((await request('/v1/form-session',undefined,'forged')).status).toBe(403);db.raw.exec('UPDATE form_sessions SET retain_until=0');await expireFormAnswers(env);expect((db.raw.prepare('SELECT encrypted_answers FROM form_sessions WHERE id=?').get(a.id) as any).encrypted_answers).toBeNull();expect((await (await request(base+'/'+id+'/submissions/'+a.id)).json() as any).answers).toBeNull();
 });
 it('separates test submissions and prepares a real mapped action exactly once without sending it',async()=>{
  await enabled();db.raw.prepare('INSERT INTO business_connectors(id,tenant_id,project_id,name,config_json,encrypted_credentials,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run('b','t','p','CRM',JSON.stringify({origin:'https://example.test',actions:['create_ticket']}),await encryptText('{}',env.MASTER_KEY),'active',0,0);db.raw.exec("INSERT INTO business_connector_bindings VALUES('t','p','s','b',0)");const def={title:'Issue',fields:[{key:'title',label:'Summary',type:'text',required:true},{key:'description',label:'Description',type:'textarea',required:true}],action:{connector_id:'b',operation:'create_ticket',input_fields:{title:'title',description:'description'}}};const id=await create(def);const test=await (await request(base+'/'+id+'/test',{})).json() as any;await submit(test.token,{title:'Test',description:'Test only'});expect((await request(base+'/'+id+'/submissions/'+test.id+'/propose',{confirm:true})).status).toBe(404);await activate(id);const s=await start(id);expect(s.definition.action).toBeUndefined();await submit(s.token,{title:'Real request',description:'Customer details'});const one=await (await request(base+'/'+id+'/submissions/'+s.id+'/propose',{confirm:true})).json() as any;const two=await (await request(base+'/'+id+'/submissions/'+s.id+'/propose',{confirm:true})).json() as any;expect(one.status).toBe('pending');expect(one.id).toBe(two.id);expect(db.raw.prepare('SELECT * FROM business_connector_runs').all()).toHaveLength(0);
 });
 it('rolls back form writes when audit persistence fails and ships parseable UI scripts',async()=>{
  await enabled();db.raw.exec("CREATE TRIGGER reject_form_audit BEFORE INSERT ON audit_logs BEGIN SELECT RAISE(ABORT,'secret'); END");expect((await request(base,definition())).status).toBe(503);expect(db.raw.prepare('SELECT * FROM interactive_forms').all()).toHaveLength(0);for(const file of ['form-builder.js','form-runtime.js'])expect(()=>new Function(readFileSync(new URL('../../web/public/'+file,import.meta.url),'utf8'))).not.toThrow();
 });
});
