ALTER TABLE plans ADD COLUMN max_knowledge_bases INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN max_documents INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN max_storage_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE plans ADD COLUMN max_vector_chunks INTEGER NOT NULL DEFAULT 0;