import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const {token}=JSON.parse(execFileSync('cmd.exe',['/c','pnpm.cmd exec wrangler auth token --json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
const base='https://api.cloudflare.com/client/v4/accounts/55f76f1c600f103ac0eed0d2c4bf36e9/workers/scripts/dlogicai-api-uat';
const headers={Authorization:`Bearer ${token}`};
const manifest=JSON.parse(readFileSync('.tmp/uat-isolated/release-manifest.json','utf8'));
const current=await fetch(base,{headers});
if(!current.ok) throw new Error('Unable to check deployed code');
const parts=await current.formData();
const code=String(parts.get('index.js'));
if(createHash('sha256').update(code).digest('hex')!==manifest.originalSha256) throw new Error('UAT changed since snapshot; aborting');
const release=readFileSync('.tmp/uat-isolated/release.mjs','utf8');
if(createHash('sha256').update(release).digest('hex')!==manifest.releaseSha256) throw new Error('Release hash mismatch');
const body=new FormData();
body.set('metadata',JSON.stringify({main_module:'index.js'}));
body.set('index.js',new Blob([release],{type:'application/javascript+module'}),'index.js');
const response=await fetch(base+'/content',{method:'PUT',headers,body});
const data=await response.json();
if(!response.ok||!data.success) throw new Error(`UAT content upload failed ${response.status}: ${(data.errors||[]).map(x=>x.code).join(',')}`);
writeFileSync('.tmp/uat-isolated/deploy-result.json',JSON.stringify(data.result,null,2));
console.log(JSON.stringify({success:true,id:data.result.id,etag:data.result.etag,modified_on:data.result.modified_on}));
const after=await (await fetch(base+'/settings',{headers})).json();
const before=JSON.parse(readFileSync('.tmp/uat-isolated/deployed-settings.json','utf8'));
const normalize=x=>JSON.stringify([...x.bindings].sort((a,b)=>a.name.localeCompare(b.name)));
if(normalize(after.result)!==normalize(before)) throw new Error('Bindings changed unexpectedly');
console.log('All existing UAT bindings preserved');
const health=await fetch('https://dlogicai-api-uat.rdproducts-adm1.workers.dev/health');
console.log(JSON.stringify({healthStatus:health.status,health:await health.json()}));
